apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    costcenter: local
    location: Seoul
    type: webserver
spec:
  containers:
    - name: nginx-container
      image: nginx
